# This file is combined with the regular docker compose file
# to bind debug ports to the local ports. Only one of these 
# will actually be used, however, depending on what the 
# value of the DEBUG environment variable is set when the 
# make command is run.

version: '3'
services:
  mail-service:
    ports:
      - "9080:40000"
    build:
      dockerfile: mail-service.debug.dockerfile
