version: '3'
services:

  broker-service:
    container_name: broker-service
    build:
      context: ../broker-service
      dockerfile: broker-service.dockerfile # Relative to the context location
    restart: always
    ports:
      - "8080:80" # Map 8080 on our machine to 8080 on the container
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    container_name: logger-service
    build:
      context: ../logger-service
      dockerfile: logger-service.dockerfile # Relative to the context location
    restart: always
    ports:
      - "8081:80" # Map 8081 on our machine to 8081 on the container
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    container_name: authentication-service
    build:
      context: ../authentication-service
      dockerfile: authentication-service.dockerfile
    restart: always
    environment:
      DSN: 'host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=5'

  postgres:
    container_name: postgres
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ../db/postgres/:/var/lib/postgresql/data/ # Data Volume
      - ../db/scripts/setup.sql:/docker-entrypoint-initdb.d/01-setup.sql # Start up Script

  mongo:
    container_name: mongo
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ../db/mongo/:/data/db
